CREATE DATABASE mydb2;
USE mydb2;

CREATE TABLE Board (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
    body VARCHAR(2000) NOT NULL,
	inserted DATETIME NOT NULL DEFAULT NOW()
);

CREATE TABLE reply (
	id INT PRIMARY KEY AUTO_INCREMENT,
	board_id INT , -- foreign key(참조키, 외래키)
    FOREIGN KEY (board_id) REFERENCES Board(id), -- FOREIGN KEY 제약사항 추가
	content VARCHAR(255) NOT NULL,
    inserted DATETIME DEFAULT NOW()
);

SELECT * FROM Board;

SET SQL_SAFE_UPDATES = 0;
UPDATE Board
SET inserted = DATE_SUB(inserted, INTERVAL 1 DAY);






